  runtime: nodejs22
  env: standard
  service: smart-stack-service

  handlers:
    - url: /_next/static
      static_dir: .next/static
      expiration: "30d"

    - url: /(.*\.(gif|png|jpg|jpeg|webp|ico|svg|css|js))$
      static_files: public/\1
      upload: public/(.*\.(gif|png|jpg|jpeg|webp|ico|svg|css|js))$
      expiration: "30d"

    - url: /.*
      script: auto

  env_variables:
    CLOUD_SQL_CONNECTION_NAME: "durable-melody-460304-t5:us-central1:smart-stack-db"
    CLOUD_SQL_DATABASE: "product_catalog"
    CLOUD_SQL_USER: "smart-stack-db-user"
    CLOUD_SQL_IAM_USER: "456529870691-compute"
    CLOUD_SQL_PASSWORD: "2;j>.GXXPq~zNrNx"
    NODE_ENV: "production"
    CLOUDSQL_DB_HOST: 34.28.152.143
    PUBLIC_IP: true